-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2011 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions
-- and other software and tools, and its AMPP partner logic
-- functions, and any output files from any of the foregoing
-- (including device programming or simulation files), and any
-- associated documentation or information are expressly subject
-- to the terms and conditions of the Altera Program License
-- Subscription Agreement, Altera MegaCore Function License
-- Agreement, or other applicable license agreement, including,
-- without limitation, that your use is for the sole purpose of
-- programming logic devices manufactured by Altera and sold by
-- Altera or its authorized distributors.  Please refer to the
-- applicable agreement for further details.


-- Generated by Quartus II 32-bit Version 11.1 (Build Build 216 11/23/2011)
-- Created on Fri May 17 13:17:55 2013

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY X16bit_4_to_1_mux IS
-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
PORT
(
data0 : IN STD_LOGIC_VECTOR(15 downto 0);
data1 : IN STD_LOGIC_VECTOR(15 downto 0);
data2 : IN STD_LOGIC_VECTOR(15 downto 0);
data3 : IN STD_LOGIC_VECTOR(15 downto 0);
sel : IN STD_LOGIC_VECTOR(1 downto 0);
output : OUT STD_LOGIC_VECTOR(15 downto 0)
);
-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

END X16bit_4_to_1_mux;


--  Architecture Body

ARCHITECTURE X16bit_4_to_1_mux OF X16bit_4_to_1_mux IS


BEGIN
	output <= 
				data3 when sel = "11" else
				data1 when sel = "01" else
				data2 when sel = "10" else 
				data0;

END X16bit_4_to_1_mux;
